## 1. Feladatsor

### 1.feladat: Az interaktív konzol 
MATLAB mint számológép

#### Próbáljuk ki a különböző alapműveleteket.

In [1]:
1+2
1.5 * 3
2/3
3^2
mod(10, 3)
idivide(10, 3)
~1
~0

ans =  3
ans =  4.5000
ans =  0.66667
ans =  9
ans =  1
ans =  3
ans = 0
ans = 1


#### Hasonlítsunk össze két értéket.

In [2]:
1 == 1
1 == 2

1 ~= 1
1 ~= 2.5

ans = 1
ans = 0
ans = 0
ans = 1


In [3]:
1 < 2
1 <= 1

ans = 1
ans = 1


####  Használjunk logikai műveleteket.

In [4]:
(1 == 1) && (2 == 2)
(mod(10, 2) == 0) || (mod(10,2) == 1)

ans = 1
ans = 1


####  Változók, értékadás.

In [5]:
valtozo_nev = "ertek"
x = 2
x += 2 % -=, *=, /=, ...
x = x + 2

valtozo_nev = ertek
x =  2
x =  4
x =  6


####  Definiáljunk vektorokat, mátrixokat.

In [6]:
A = [1 0;
     0 1]

oszlop_b = [1; 1]
sor_b = [1, 1]
b = oszlop_b;

A =

   1   0
   0   1

oszlop_b =

   1
   1

sor_b =

   1   1



In [7]:
oszlop_b'

ans =

   1   1



In [8]:
% Indexing
b(1)

[1,2,3,4,5](2:3)
[1,2,3,4,5](1:2:end)

ans =  1
ans =

   2   3

ans =

   1   3   5



In [9]:
A(1:2, 1:2)
A(2,2)
A(:)'

ans =

   1   0
   0   1

ans =  1
ans =

   1   0   0   1



#### Próbáljunk ki néhány vektorműveletet.

In [10]:
A *= 2
b
b - 3

b .* [5; 2]
b ./ [5; pi]

A * b
A \ b

A =

   2   0
   0   2

b =

   1
   1

ans =

  -2
  -2

ans =

   5
   2

ans =

   0.20000
   0.31831

ans =

   2
   2

ans =

   0.50000
   0.50000



#### Dolgozzunk komplex számokkal.

In [11]:
(0+1i) * 1i
abs(1i)
real(3+4i)
imag(3+4i)

ans = -1
ans =  1
ans =  3
ans =  4


#### További hasznos beépített függvények, utasítások.

In [12]:
c = 1:10

c =

    1    2    3    4    5    6    7    8    9   10



In [13]:
1:2:10

ans =

   1   3   5   7   9



In [14]:
0:.5:2
linspace(0, 2, 5)

ans =

    0.00000    0.50000    1.00000    1.50000    2.00000

ans =

   0.00000   0.50000   1.00000   1.50000   2.00000



In [15]:
ndims(c)
numel(c)

ans =  2
ans =  10


In [16]:
size(c)
[n, m] = size(c)

ans =

    1   10

n =  1
m =  10


In [17]:
sum(c)
prod(c)

ans =  55
ans =  3628800


In [18]:
abs((-1)*c)

ans =

    1    2    3    4    5    6    7    8    9   10



In [19]:
all(2*[1,1,1])
all([0,1,1])

ans = 1
ans = 0


In [20]:
any([0,0,0])
any([0,1,0])

ans = 0
ans = 1


In [21]:
zeros(2)
ones(2,3)

ans =

   0   0
   0   0

ans =

   1   1   1
   1   1   1



In [22]:
eye(2)
diag([1,2,3])

ans =

Diagonal Matrix

   1   0
   0   1

ans =

Diagonal Matrix

   1   0   0
   0   2   0
   0   0   3



In [23]:
A=[1 0 0; 
   0 2 0;
   0 0 1];
   
trace(A)
det(A)

ans =  4
ans =  2


In [24]:
lam = eig(A)
[V, LAMBDA] = eig(A)

lam =

   1
   1
   2

V =

   1   0   0
   0   0   1
   0   1   0

LAMBDA =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   2



In [25]:
diag(LAMBDA)

diag(diag(LAMBDA))

diag(diag(LAMBDA)) == LAMBDA

all(diag(diag(LAMBDA)) == LAMBDA)

all(all(diag(diag(LAMBDA)) == LAMBDA))

ans =

   1
   1
   2

ans =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   2

ans =

  1  1  1
  1  1  1
  1  1  1

ans =

  1  1  1

ans = 1


In [ ]:
help eig

### 2.feladat: Egy kis programozás
MATLAB mint programnyelv (csak az alapok, példákon keresztül)

#### Függvények

In [27]:
function r = add_(x, y)
    r = x+y;
end

In [28]:
x = add_(2, 3)

x =  5


In [29]:
[n, m] = size(A)

n =  3
m =  3


In [30]:
function visszateresi_valtozo = fuggveny_neve(parameter1, parameter2)

end %endfunction

In [31]:
% anonim fgv. 
@(x)(x+2)
arrayfun(@(x)(x+2), [1,2,3])

ans =

@(x) (x + 2)

ans =

   3   4   5



#### Elágazások

In [32]:
function s = if_else_pelda(x)
    if (x == 0)
       s = "0";
    elseif (x == 1)
       s = "1";
    elseif (x == 2)
       s = "2";
    else
       s = "?";
    end
end
if_else_pelda(0)
if_else_pelda(1)
if_else_pelda(2)
if_else_pelda(42)

ans = 0
ans = 1
ans = 2
ans = ?


In [33]:
function s = if_else_pelda2(x)
    if ismember(x, [0,1,2])
        s = int2str(x);
    else
        s = "?";
    end
end
if_else_pelda2(0)
if_else_pelda2(1)
if_else_pelda2(2)
if_else_pelda2(42)

ans = 0
ans = 1
ans = 2
ans = ?


#### Ciklusok

In [34]:
3:5

ans =

   3   4   5



In [35]:
for v=3:5
   v
end

v =  3
v =  4
v =  5


In [36]:
arr = 3:5
for v=arr
   v
end

for ix=1:numel(arr)
   ix
   arr(ix)
end

arr =

   3   4   5

v =  3
v =  4
v =  5
ix =  1
ans =  3
ix =  2
ans =  4
ix =  3
ans =  5


In [37]:
ix = 1;
while ix <= numel(arr)
  arr(ix)
  ix += 1
end

ans =  3
ix =  2
ans =  4
ix =  3
ans =  5
ix =  4


In [38]:
A = magic(2)
[m,n] = size(A);

for i=1:m
    for j=1:n
       i,j
       A(i,j)
    end
end

A =

   4   3
   1   2

i =  1
j =  1
ans =  4
i =  1
j =  2
ans =  3
i =  2
j =  1
ans =  1
i =  2
j =  2
ans =  2


### 3.feladat: Sajátérték-e a 0?

Az eddigiek felhasználásával irjunk olyan mátrix bemenetű függvényt, ami eldönti, hogy a bemenetnek a 0 sajátértéke-e. Próbáljuk meg először ciklussal, majd anélkül.

In [39]:
function zero_is_eig = is_zero_eigenvalue(A)
     eigs = eig(A);
     
     zero_is_eig = 0;
     
     for ix=1:numel(eigs)
        if eigs(ix) == 0
            zero_is_eig = 1;
        end
     end
endfunction

is_zero_eigenvalue(ones(2))
is_zero_eigenvalue(eye(2))

ans =  1
ans = 0


In [40]:
ismember(0, eigs(ones(2)))
ismember(0, eigs(eye(2)))

ans = 1
ans = 0


### 4.feladat: Sajátérték-e?

Az előző feladat megoldását általánosítsuk úgy, hogy a 0 helyett más számról is el lehessen dönteni, hogy sajátérték-e.

In [41]:
function lam_is_eig = is_eigenvalue(A, lam)
    % ...
endfunction

In [42]:
% is_eigenvalue.m